### ISSUE TITLE
Support GHC 9.2.*

### ISSUE THREAD

**Issue by futu2** [fjvallarino/monomer#202]
When built with GHC 9.2.3 and 9.2.4, encountering error

```
[ 83 of 104] Compiling Monomer.Widgets.Containers.Dropdown ( src/Monomer/Widgets/Containers/Dropdown.hs, dist/build/Monomer/Widgets/Containers/Dropdown.o, dist/build/Monomer/Widgets/Containers/Dropdown.dyn_o )

src/Monomer/Widgets/Containers/Dropdown.hs:423:3: error:
    • Illegal equational constraint Control.Lens.At.Index a2 ~ Int
      (Use GADTs or TypeFamilies to permit this)
    • When checking the inferred type
        scrollListInfo :: forall {s} {a1} {b} {a2} {p}.
                          (L.HasWidgetId s a1, L.HasPath s b, Control.Lens.At.Index a2 ~ Int,
                           L.HasChildren p a2, Control.Lens.At.Ixed a2,
                           L.HasInfo (Control.Lens.At.IxValue a2) s) =>
                          p -> (a1, b)
      In an equation for ‘makeDropdown’:
          makeDropdown widgetData items makeMain makeRow config state
            = widget
            where
```

**Comment by Dretch** [comment]
This looks like the issue that was fixed in #159.

There is not currently a release version with the fix, but you can might be able to use the unreleased code. E.g. with stack, put something like in your stack.yaml:

```yaml
extra-deps:
  # for the latest fixes
- git: "https://github.com/fjvallarino/monomer"
  commit: "7b1d59d754d75588aae1097a231712264cf61719"
```
